### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Sloth#108]
For transactions, be able to search by merchant id in a team.
Return the index filter to that.
Maybe also have a search for the Processor Tracking number and KFS Tracking number

**Comment by jSylvestre** [comment]
If you search for the Processor tracking number, return all the transactions related to it (Find the transaction, then return all the transactions with the same merchant id for that team.

**Comment by sprucely** [comment]
Should I try to keep the url pretty for these additional filters?
`/payments/Transactions/Filtered/2020-02-29/2020-03-31/TeamMerchant/true/TrkNumProcessing/456`
Rather than make the route long and complex, I could just ad a catch-all variable at the end and parse the string.

 Or I could just revert to using query parameters?
`/payments/Transactions/Filtered/2020-02-29/2020-03-31?TeamMerchant=true&TrkNumProcessing=456`
This would allow us to remove the custom route.

**Comment by jSylvestre** [comment]
@sprucely  I do like the look of the custom route, but I'd just use the query parameters.

**Comment by sprucely** [comment]
> For transactions, be able to search by merchant id in a team.
Return the index filter to that.

Do you mean only the merchant id associated with the current slug (ie: just a checkbox?) Or should there be a dropdown to allow filtering by merchant id for any given team?

I just noticed that merchant id isn't unique to a team but part of a many-to-many relationship between Sources and Teams. Is it safe to assume that a given merchant id will only ever be associated with a single team?

**Comment by jSylvestre** [comment]
@sprucely No, the merchant id isn't unique. We usually just use the id (int) of the invoice or order.
So when searching, you want to filter by the slug (team).
I don't think we care about searching across teams.

**Comment by sprucely** [comment]
Would it be acceptable to have a single "TrackingNumber" field that is used to search all three (kfs, merchant and processing)?

**Comment by jSylvestre** [comment]
@sprucely  I think that would be fine.  For The column size and indexes, just create an issue for now.

**Comment by sprucely** [comment]
Search implemented in pull request #110 and merged to master
